<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGo8xa9g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGo8xa9g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGo8xa9g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGo8xa9g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGo8xa9g\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Go8xa9g',
    'container.build_id' => '5f8044d5',
    'container.build_time' => 1535853222,
));
