<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Calculator extends \AppBundle\Entity\Calculator implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'formalizacion', 'vencimiento', 'dias', 'nominal', 'honorarios', 'timbres', 'omf', 'mensajeria', 'burofax', 'gastos', 'costeFinanciero', 'costeFinancieroLedser', 'costeTotal', '' . "\0" . 'AppBundle\\Entity\\Calculator' . "\0" . 'proposal', 'id', 'createdAt', 'updatedAt'];
        }

        return ['__isInitialized__', 'formalizacion', 'vencimiento', 'dias', 'nominal', 'honorarios', 'timbres', 'omf', 'mensajeria', 'burofax', 'gastos', 'costeFinanciero', 'costeFinancieroLedser', 'costeTotal', '' . "\0" . 'AppBundle\\Entity\\Calculator' . "\0" . 'proposal', 'id', 'createdAt', 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Calculator $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFormalizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormalizacion', []);

        return parent::getFormalizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormalizacion($formalizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormalizacion', [$formalizacion]);

        return parent::setFormalizacion($formalizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimiento', []);

        return parent::getVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimiento($vencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimiento', [$vencimiento]);

        return parent::setVencimiento($vencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDias', []);

        return parent::getDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setDias($dias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDias', [$dias]);

        return parent::setDias($dias);
    }

    /**
     * {@inheritDoc}
     */
    public function getNominal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNominal', []);

        return parent::getNominal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNominal($nominal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNominal', [$nominal]);

        return parent::setNominal($nominal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosteFinanciero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosteFinanciero', []);

        return parent::getCosteFinanciero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosteFinanciero($costeFinanciero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosteFinanciero', [$costeFinanciero]);

        return parent::setCosteFinanciero($costeFinanciero);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosteFinancieroLedser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosteFinancieroLedser', []);

        return parent::getCosteFinancieroLedser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosteFinancieroLedser($costeFinancieroLedser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosteFinancieroLedser', [$costeFinancieroLedser]);

        return parent::setCosteFinancieroLedser($costeFinancieroLedser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosteTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosteTotal', []);

        return parent::getCosteTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosteTotal($costeTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosteTotal', [$costeTotal]);

        return parent::setCosteTotal($costeTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHonorarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHonorarios', []);

        return parent::getHonorarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setHonorarios($honorarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHonorarios', [$honorarios]);

        return parent::setHonorarios($honorarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimbres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimbres', []);

        return parent::getTimbres();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimbres($timbres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimbres', [$timbres]);

        return parent::setTimbres($timbres);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmf', []);

        return parent::getOmf();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmf($omf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmf', [$omf]);

        return parent::setOmf($omf);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensajeria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensajeria', []);

        return parent::getMensajeria();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensajeria($mensajeria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensajeria', [$mensajeria]);

        return parent::setMensajeria($mensajeria);
    }

    /**
     * {@inheritDoc}
     */
    public function getBurofax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBurofax', []);

        return parent::getBurofax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBurofax($burofax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBurofax', [$burofax]);

        return parent::setBurofax($burofax);
    }

    /**
     * {@inheritDoc}
     */
    public function getGastos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGastos', []);

        return parent::getGastos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGastos($gastos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGastos', [$gastos]);

        return parent::setGastos($gastos);
    }

    /**
     * {@inheritDoc}
     */
    public function getProposal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProposal', []);

        return parent::getProposal();
    }

    /**
     * {@inheritDoc}
     */
    public function setProposal($proposal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProposal', [$proposal]);

        return parent::setProposal($proposal);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
